name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
              version: '5.15.2'
              target: 'desktop'
      - name: install boost
        uses: MarkusJx/install-boost@v2.4.1
        with:
              boost_version: '1.80.0'
              version: 22.04
              toolset: 'gcc'
      - name: build ios
        run: |
          mkdir build
          cd build
          cmake ..
          make
